services:
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: wep-fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin123
    volumes:
      - fuseki_data:/fuseki

  backend:
    build: ./backend
    container_name: wep-backend
    ports:
      - "8000:8000"
    environment:
      - FUSEKI_URL=http://fuseki:3030
    depends_on:
      - fuseki
    volumes:
      - ./backend:/app
      - /app/__pycache__

  frontend:
    build: ./frontend
    container_name: wep-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://54.72.245.20:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  fuseki_data:
